#ifndef IRODS_GENQUERY2_DRIVER_HPP
#define IRODS_GENQUERY2_DRIVER_HPP

#include "irods/private/genquery2_scanner.hpp"
#include "irods/private/genquery2_ast_types.hpp" // For irods::experimental::genquery2::select.

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

#include <string>

// Give the expected function signature of the yylex() function to flex.
// The parameter, drv, is required. It is referenced by the flex script, lexer.l.
// This is an easy alternative to the "%code provides" directive in parser.y.
//#undef  YY_DECL
//#define YY_DECL yy::parser::symbol_type scanner::yylex(irods::experimental::genquery2::driver& drv)

namespace irods::experimental::genquery2
{
    /// Coordinates scanning and parsing for GenQuery2 input.
    class driver
    {
      public:
        /// Constructs an empty GenQuery2 driver.
        driver() = default;

        /// Parses a GenQuery2 string and populates the generated AST.
        ///
        /// \param[in] _s The GenQuery2 string to parse.
        /// \return Zero on success, or a non-zero parser error code on failure.
        auto parse(const std::string& _s) -> int;

        /// The AST-like representation produced by the parser.
        irods::experimental::genquery2::select select;

        /// The Flex scanner implementation.
        scanner lexer;

        /// The current parser location.
        yy::location location;

        /// Temporary storage for string literals captured by the lexer.
        std::string string_literal;
    }; // class driver
} // namespace irods::experimental::genquery2

#endif // IRODS_GENQUERY2_DRIVER_HPP
