# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "/src/irods;/src/irods/build_wdt")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "irods-database-plugin-mysql;irods-database-plugin-oracle;irods-database-plugin-postgres;irods-dev;irods-runtime;irods-server")
set(CPACK_COMPONENTS_GROUPING "IGNORE")
set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_COMPRESSION_TYPE "gzip")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_CONFLICTS "irods-database-plugin-postgres, irods-database-plugin-oracle")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_CONTROL_EXTRA "/src/irods/plugins/database/packaging/preinst;/src/irods/plugins/database/packaging/postinst;/src/irods/plugins/database/packaging/postrm;")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_DEPENDS "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server (= 5.0.90-0~noble), unixodbc, libodbc2, odbcinst, virtual-mysql-client, libc6, libgcc-s1, libstdc++6")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_NAME "irods-database-plugin-mysql")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_PROVIDES "irods-database-plugin-mysql (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-MYSQL_PACKAGE_RECOMMENDS "odbc-mariadb | mariadb-connector-odbc | mysql-connector-odbc | mysql-connector-odbc-commercial | libmyodbc")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-ORACLE_PACKAGE_CONFLICTS "irods-database-plugin-mysql, irods-database-plugin-postgres")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-ORACLE_PACKAGE_CONTROL_EXTRA "/src/irods/plugins/database/packaging/preinst;/src/irods/plugins/database/packaging/postinst;/src/irods/plugins/database/packaging/postrm;")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-ORACLE_PACKAGE_DEPENDS "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server (= 5.0.90-0~noble), unixodbc, libodbc2, odbcinst, libc6, libgcc-s1, libstdc++6")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-ORACLE_PACKAGE_NAME "irods-database-plugin-oracle")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-ORACLE_PACKAGE_PROVIDES "irods-database-plugin-oracle (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-POSTGRES_PACKAGE_CONFLICTS "irods-database-plugin-mysql, irods-database-plugin-oracle")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-POSTGRES_PACKAGE_CONTROL_EXTRA "/src/irods/plugins/database/packaging/preinst;/src/irods/plugins/database/packaging/postinst;/src/irods/plugins/database/packaging/postrm;")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-POSTGRES_PACKAGE_DEPENDS "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server (= 5.0.90-0~noble), unixodbc, libodbc2, odbcinst, odbc-postgresql, postgresql-client, libc6, libgcc-s1, libstdc++6")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-POSTGRES_PACKAGE_NAME "irods-database-plugin-postgres")
set(CPACK_DEBIAN_IRODS-DATABASE-PLUGIN-POSTGRES_PACKAGE_PROVIDES "irods-database-plugin-postgres (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_CONFLICTS "irods-experimental-api-plugin-genquery2")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_DEPENDS "irods-externals-clang16.0.6-0, irods-externals-jsoncons0.178.0-0, irods-runtime (= 5.0.90-0~noble), libssl-dev, libcurl-dev, libfmt-dev, libspdlog-dev, nlohmann-json3-dev")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_NAME "irods-dev")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_PROVIDES "irods-dev (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_RECOMMENDS "libcurl4-gnutls-dev")
set(CPACK_DEBIAN_IRODS-DEV_PACKAGE_REPLACES "irods-runtime (<< 4.3.0~)")
set(CPACK_DEBIAN_IRODS-RUNTIME_PACKAGE_DEPENDS "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, libc6, sudo, libfuse2, libxml2, openssl, libcurl3-gnutls, libfmt9, libspdlog1.12, libgcc-s1, libstdc++6, libssl3")
set(CPACK_DEBIAN_IRODS-RUNTIME_PACKAGE_NAME "irods-runtime")
set(CPACK_DEBIAN_IRODS-RUNTIME_PACKAGE_PROVIDES "irods-runtime (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-RUNTIME_PACKAGE_REPLACES "irods-server (<< 4.2.10-2~)")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_BREAKS "irods-icat, irods-resource")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_CONFLICTS "irods-experimental-api-plugin-genquery2")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_CONTROL_EXTRA "/src/irods/preinst;/src/irods/postinst;/src/irods/prerm;")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_DEPENDS "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-runtime (= 5.0.90-0~noble), libc6, sudo, libssl3, libfuse2, python3, openssl, python3-psutil, python3-pyodbc, python3-jsonschema, python3-distro, libarchive13, lsof, libgcc-s1, libstdc++6")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_NAME "irods-server")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_PROVIDES "irods, irods-server (= 5.0.90)")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_RECOMMENDS "irods-icommands (>= 5.0.90)")
set(CPACK_DEBIAN_IRODS-SERVER_PACKAGE_REPLACES "irods-icat, irods-resource")
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION "ON")
set(CPACK_DEBIAN_PACKAGE_DEPENDS_CURL "libcurl3-gnutls")
set(CPACK_DEBIAN_PACKAGE_DEPENDS_CURL_DEV "libcurl4-gnutls-dev")
set(CPACK_DEBIAN_PACKAGE_DEPENDS_LIBODBC "libodbc2")
set(CPACK_DEBIAN_PACKAGE_DEPENDS_SPDLOG "libspdlog1.12")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "extra")
set(CPACK_DEBIAN_PACKAGE_RELEASE "0~noble")
set(CPACK_DEBIAN_PACKAGE_SECTION "contrib/science")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "OFF")
set(CPACK_DEBIAN_PACKAGE_VERSION "5.0.90")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "irods built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/src/irods;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/")
set(CPACK_MODULE_PATH "/src/irods/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "irods 5.0.90")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "irods 5.0.90")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/opt/irods-externals/clang16.0.6-0/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/opt/irods-externals/clang16.0.6-0/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/src/irods/build_wdt/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "iRODS Consortium <packages@irods.org>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "The Integrated Rule-Oriented Data System (iRODS) is open source data management software used by research, commercial, and governmental organizations worldwide.

iRODS is released as a production-level distribution aimed at deployment in mission critical environments. It virtualizes data storage resources, so users can take control of their data, regardless of where and on what device the data is stored.

The development infrastructure supports exhaustive testing on supported platforms; plugin support for microservices, storage resources, authentication mechanisms, network protocols, rule engines, new API endpoints, and databases; and extensive documentation, training, and support services.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/src/irods/build_wdt/CMakeFiles/CPack_package_description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Integrated Rule-Oriented Data System")
set(CPACK_PACKAGE_FILE_NAME "irods-5.0.90-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://irods.org")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "irods 5.0.90")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "irods 5.0.90")
set(CPACK_PACKAGE_NAME "irods")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "iRODS Consortium <packages@irods.org>")
set(CPACK_PACKAGE_VERSION "5.0.90")
set(CPACK_PACKAGE_VERSION_MAJOR "5")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "90")
set(CPACK_PACKAGING_INSTALL_PREFIX "/")
set(CPACK_READELF_EXECUTABLE "/opt/irods-externals/clang16.0.6-0/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.28/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_COMPRESSION_TYPE "gzip")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/sbin;/lib")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_AUTOPROV "0")
set(CPACK_RPM_PACKAGE_AUTOREQ "0")
set(CPACK_RPM_PACKAGE_LICENSE "BSD-3-Clause")
set(CPACK_RPM_PACKAGE_RELEASE "0.el24")
set(CPACK_RPM_PACKAGE_RELOCATABLE "ON")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_SUMMARY "The Integrated Rule-Oriented Data System")
set(CPACK_RPM_SPEC_MORE_DEFINE "%global __python %{__python3}
%global __brp_check_rpaths %{nil}")
set(CPACK_RPM_irods-database-plugin-mysql_PACKAGE_CONFLICTS "irods-database-plugin-postgres, irods-database-plugin-oracle")
set(CPACK_RPM_irods-database-plugin-mysql_PACKAGE_NAME "irods-database-plugin-mysql")
set(CPACK_RPM_irods-database-plugin-mysql_PACKAGE_REQUIRES "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server = -0.el24, unixODBC, (mariadb or mysql or mariadb-client or mysql-client or MariaDB-client or MySQL-client or mysql-compat-client), (mariadb-connector-odbc or mysql-connector-odbc), glibc, libgcc, libstdc++")
set(CPACK_RPM_irods-database-plugin-mysql_POST_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postinst")
set(CPACK_RPM_irods-database-plugin-mysql_POST_UNINSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postrm")
set(CPACK_RPM_irods-database-plugin-mysql_PRE_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/preinst")
set(CPACK_RPM_irods-database-plugin-oracle_PACKAGE_CONFLICTS "irods-database-plugin-mysql, irods-database-plugin-postgres")
set(CPACK_RPM_irods-database-plugin-oracle_PACKAGE_NAME "irods-database-plugin-oracle")
set(CPACK_RPM_irods-database-plugin-oracle_PACKAGE_REQUIRES "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server = -0.el24, unixODBC, glibc, libgcc, libstdc++")
set(CPACK_RPM_irods-database-plugin-oracle_POST_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postinst")
set(CPACK_RPM_irods-database-plugin-oracle_POST_UNINSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postrm")
set(CPACK_RPM_irods-database-plugin-oracle_PRE_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/preinst")
set(CPACK_RPM_irods-database-plugin-postgres_PACKAGE_CONFLICTS "irods-database-plugin-mysql, irods-database-plugin-oracle")
set(CPACK_RPM_irods-database-plugin-postgres_PACKAGE_NAME "irods-database-plugin-postgres")
set(CPACK_RPM_irods-database-plugin-postgres_PACKAGE_REQUIRES "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-server = -0.el24, unixODBC, postgresql, postgresql-odbc, glibc, libgcc, libstdc++")
set(CPACK_RPM_irods-database-plugin-postgres_POST_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postinst")
set(CPACK_RPM_irods-database-plugin-postgres_POST_UNINSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/postrm")
set(CPACK_RPM_irods-database-plugin-postgres_PRE_INSTALL_SCRIPT_FILE "/src/irods/plugins/database/packaging/preinst")
set(CPACK_RPM_irods-dev_PACKAGE_CONFLICTS "irods-experimental-api-plugin-genquery2")
set(CPACK_RPM_irods-dev_PACKAGE_NAME "irods-devel")
set(CPACK_RPM_irods-dev_PACKAGE_OBSOLETES "irods-dev")
set(CPACK_RPM_irods-dev_PACKAGE_REQUIRES "irods-externals-clang16.0.6-0, irods-externals-jsoncons0.178.0-0, irods-runtime = -0.el24, libcurl-devel, nlohmann_json-devel, fmt-devel, spdlog-devel, openssl-devel")
set(CPACK_RPM_irods-runtime_PACKAGE_NAME "irods-runtime")
set(CPACK_RPM_irods-runtime_PACKAGE_REQUIRES "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, libxml2, libcurl, openssl, glibc, fmt, spdlog, libgcc, libstdc++")
set(CPACK_RPM_irods-runtime_POST_INSTALL_SCRIPT_FILE "/src/irods/packaging/runtime_library_postinst.sh")
set(CPACK_RPM_irods-server_PACKAGE_CONFLICTS "eirods, irods-experimental-api-plugin-genquery2")
set(CPACK_RPM_irods-server_PACKAGE_NAME "irods-server")
set(CPACK_RPM_irods-server_PACKAGE_OBSOLETES "irods-icat, irods-resource")
set(CPACK_RPM_irods-server_PACKAGE_PROVIDES "irods")
set(CPACK_RPM_irods-server_PACKAGE_REQUIRES "irods-externals-boost1.81.0-2, irods-externals-nanodbc2.13.0-3, irods-runtime = -0.el24, openssl, python3, python3-psutil, libarchive, chkconfig, glibc, libgcc, libstdc++, python3-jsonschema, python3-distro, python3-pyodbc")
set(CPACK_RPM_irods-server_PACKAGE_SUGGESTS "irods-icommands = ")
set(CPACK_RPM_irods-server_POST_INSTALL_SCRIPT_FILE "/src/irods/postinst")
set(CPACK_RPM_irods-server_PRE_INSTALL_SCRIPT_FILE "/src/irods/preinst")
set(CPACK_RPM_irods-server_PRE_UNINSTALL_SCRIPT_FILE "/src/irods/prerm")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/src/irods;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/src/irods/build_wdt/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "irods-5.0.90-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/src/irods/build_wdt/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
