#ifndef IRODS_GENQUERY1_DRIVER_HPP
#define IRODS_GENQUERY1_DRIVER_HPP

struct GenQueryInp;

#include "irods/private/genquery1_scanner.hpp"

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  undef yyFlexLexer
#  define yyFlexLexer gq1FlexLexer
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

#include <string>

namespace irods::experimental::genquery1
{
    /// Coordinates scanning and parsing for GenQuery1 input.
    class driver
    {
      public:
        /// Constructs an empty GenQuery1 driver.
        driver() = default;

        /// Parses a GenQuery1 string and populates the driver state.
        ///
        /// \param[in] _s The GenQuery1 string to parse.
        /// \return Zero on success, or a non-zero parser error code on failure.
        auto parse(const std::string& _s) -> int;

        /// The GenQuery1 input structure populated by the parser.
        GenQueryInp* gq_input = nullptr;

        /// The Flex scanner implementation.
        scanner lexer;

        /// The current parser location.
        gq1::location location;

        /// Temporary storage for string literals captured by the lexer.
        std::string string_literal;
    }; // class driver
} // namespace irods::experimental::genquery1

#endif // IRODS_GENQUERY1_DRIVER_HPP
