#ifndef AUTH_RESPONSE_H__
#define AUTH_RESPONSE_H__

#include "irods/rcConnect.h"

/**
 * \brief Input passed to `rcAuthResponse`.
 */
typedef struct {
    char *response; ///< Encoded authentication response generated by the client.
    char *username; ///< Username associated with the authentication response.
} authResponseInp_t;
#define authResponseInp_PI "bin *response(RESPONSE_LEN); str *username;"

#ifdef __cplusplus
extern "C"
#endif
int rcAuthResponse( rcComm_t *conn, authResponseInp_t *authResponseInp );

#endif
