#ifndef _HASHER_HPP_
#define _HASHER_HPP_

/// \file

#include "irods/HashStrategy.hpp"
#include "irods/irods_error.hpp"

#include <string>
#include <boost/any.hpp>

namespace irods {

    namespace hash
    {
        /// Describes formatting options for digest generation.
        struct options;
    } // namespace hash

    /// Selects strict hash policy behavior.
    const std::string STRICT_HASH_POLICY( "strict" );

    /// Selects compatible hash policy behavior.
    const std::string COMPATIBLE_HASH_POLICY( "compatible" );

    /// Produces message digests using a configured hash strategy.
    class Hasher {
        public:
            /// Constructs an uninitialized hasher.
            Hasher() : _strategy( NULL ) {}

            /// Releases any hash context held by the hasher.
            ~Hasher()
            {
                if (nullptr != _strategy) {
                    _strategy->free_context(_context);
                }
            }

            /// Initializes the hasher using the provided strategy.
            error init( const HashStrategy* );

            /// Updates the digest state using the provided string data.
            error update( const std::string& );

            /// Finalizes the digest into the provided output string.
            error digest( std::string& messageDigest );

            /// Produce a digest in string form based on the provided options.
            ///
            /// \param[in] _options \p irods::hash::options specifying how the output string should be formatted.
            /// \param[out] _out The output string.
            ///
            /// \return irods::error Any errors that are encountered are held in the returned \p irods::error.
            ///
            /// \since 5.1.0
            auto digest(const hash::options& _options, std::string& _out) -> error;

          private:
            /// Points to the active hashing strategy.
            const HashStrategy* _strategy;

            /// Holds the strategy-specific hashing context.
            boost::any          _context;

            /// Stores the most recent error generated by the hasher.
            error               _stored_error;

            /// Stores the most recent digest generated by the hasher.
            std::string         _stored_digest;
    };

}; // namespace irods

#endif // _HASHER_HPP_
