if(EXISTS "/src/irods/build_wdt/unit_tests/irods_fully_qualified_username_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_fully_qualified_username_tests-978a00a.cmake")
else()
  add_test(irods_fully_qualified_username_NOT_BUILT-978a00a irods_fully_qualified_username_NOT_BUILT-978a00a)
endif()
