if(EXISTS "/src/irods/build_wdt/unit_tests/irods_rc_mod_data_obj_meta_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_rc_mod_data_obj_meta_tests-978a00a.cmake")
else()
  add_test(irods_rc_mod_data_obj_meta_NOT_BUILT-978a00a irods_rc_mod_data_obj_meta_NOT_BUILT-978a00a)
endif()
