if(EXISTS "/src/irods/build_wdt/unit_tests/irods_re_serialization_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_re_serialization_tests-978a00a.cmake")
else()
  add_test(irods_re_serialization_NOT_BUILT-978a00a irods_re_serialization_NOT_BUILT-978a00a)
endif()
