if(EXISTS "/src/irods/build_wdt/unit_tests/irods_dstream_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_dstream_tests-978a00a.cmake")
else()
  add_test(irods_dstream_NOT_BUILT-978a00a irods_dstream_NOT_BUILT-978a00a)
endif()
