if(EXISTS "/src/irods/build_wdt/unit_tests/irods_hashers_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_hashers_tests-978a00a.cmake")
else()
  add_test(irods_hashers_NOT_BUILT-978a00a irods_hashers_NOT_BUILT-978a00a)
endif()
