if(EXISTS "/src/irods/build_wdt/unit_tests/irods_atomic_apply_acl_operations_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_atomic_apply_acl_operations_tests-978a00a.cmake")
else()
  add_test(irods_atomic_apply_acl_operations_NOT_BUILT-978a00a irods_atomic_apply_acl_operations_NOT_BUILT-978a00a)
endif()
