if(EXISTS "/src/irods/build_wdt/unit_tests/irods_lifetime_manager_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_lifetime_manager_tests-978a00a.cmake")
else()
  add_test(irods_lifetime_manager_NOT_BUILT-978a00a irods_lifetime_manager_NOT_BUILT-978a00a)
endif()
