if(EXISTS "/src/irods/build_wdt/unit_tests/irods_capped_memory_resource_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_capped_memory_resource_tests-978a00a.cmake")
else()
  add_test(irods_capped_memory_resource_NOT_BUILT-978a00a irods_capped_memory_resource_NOT_BUILT-978a00a)
endif()
