if(EXISTS "/src/irods/build_wdt/unit_tests/irods_rc_data_obj_repl_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_rc_data_obj_repl_tests-978a00a.cmake")
else()
  add_test(irods_rc_data_obj_repl_NOT_BUILT-978a00a irods_rc_data_obj_repl_NOT_BUILT-978a00a)
endif()
