if(EXISTS "/src/irods/build_wdt/unit_tests/irods_system_error_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_system_error_tests-978a00a.cmake")
else()
  add_test(irods_system_error_NOT_BUILT-978a00a irods_system_error_NOT_BUILT-978a00a)
endif()
