if(EXISTS "/src/irods/build_wdt/unit_tests/irods_process_stash_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_process_stash_tests-978a00a.cmake")
else()
  add_test(irods_process_stash_NOT_BUILT-978a00a irods_process_stash_NOT_BUILT-978a00a)
endif()
