if(EXISTS "/src/irods/build_wdt/unit_tests/irods_modern_syntax_enforcement_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_modern_syntax_enforcement_tests-978a00a.cmake")
else()
  add_test(irods_modern_syntax_enforcement_NOT_BUILT-978a00a irods_modern_syntax_enforcement_NOT_BUILT-978a00a)
endif()
