if(EXISTS "/src/irods/build_wdt/unit_tests/irods_replica_open_and_close_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_replica_open_and_close_tests-978a00a.cmake")
else()
  add_test(irods_replica_open_and_close_NOT_BUILT-978a00a irods_replica_open_and_close_NOT_BUILT-978a00a)
endif()
