if(EXISTS "/src/irods/build_wdt/unit_tests/irods_genquery1_flex_bison_parser_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_genquery1_flex_bison_parser_tests-978a00a.cmake")
else()
  add_test(irods_genquery1_flex_bison_parser_NOT_BUILT-978a00a irods_genquery1_flex_bison_parser_NOT_BUILT-978a00a)
endif()
