if(EXISTS "/src/irods/build_wdt/unit_tests/irods_json_apis_from_client_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_json_apis_from_client_tests-978a00a.cmake")
else()
  add_test(irods_json_apis_from_client_NOT_BUILT-978a00a irods_json_apis_from_client_NOT_BUILT-978a00a)
endif()
