if(EXISTS "/src/irods/build_wdt/unit_tests/irods_access_time_queue_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_access_time_queue_tests-978a00a.cmake")
else()
  add_test(irods_access_time_queue_NOT_BUILT-978a00a irods_access_time_queue_NOT_BUILT-978a00a)
endif()
