if(EXISTS "/src/irods/build_wdt/unit_tests/irods_host_list_context_string_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_host_list_context_string_tests-978a00a.cmake")
else()
  add_test(irods_host_list_context_string_NOT_BUILT-978a00a irods_host_list_context_string_NOT_BUILT-978a00a)
endif()
