if(EXISTS "/src/irods/build_wdt/unit_tests/irods_rc_switch_user_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_rc_switch_user_tests-978a00a.cmake")
else()
  add_test(irods_rc_switch_user_NOT_BUILT-978a00a irods_rc_switch_user_NOT_BUILT-978a00a)
endif()
