if(EXISTS "/src/irods/build_wdt/unit_tests/irods_user_deprecated_warnings_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_user_deprecated_warnings_tests-978a00a.cmake")
else()
  add_test(irods_user_deprecated_warnings_NOT_BUILT-978a00a irods_user_deprecated_warnings_NOT_BUILT-978a00a)
endif()
