if(EXISTS "/src/irods/build_wdt/unit_tests/irods_linked_list_iterator_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_linked_list_iterator_tests-978a00a.cmake")
else()
  add_test(irods_linked_list_iterator_NOT_BUILT-978a00a irods_linked_list_iterator_NOT_BUILT-978a00a)
endif()
