if(EXISTS "/src/irods/build_wdt/unit_tests/irods_ticket_administration_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_ticket_administration_tests-978a00a.cmake")
else()
  add_test(irods_ticket_administration_NOT_BUILT-978a00a irods_ticket_administration_NOT_BUILT-978a00a)
endif()
