if(EXISTS "/src/irods/build_wdt/unit_tests/irods_with_durability_tests-978a00a.cmake")
  include("/src/irods/build_wdt/unit_tests/irods_with_durability_tests-978a00a.cmake")
else()
  add_test(irods_with_durability_NOT_BUILT-978a00a irods_with_durability_NOT_BUILT-978a00a)
endif()
