name: azure-test

on:
  push:
  pull_request:

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Get Public IP
        run:  |
              echo ${{ matrix.os }}
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Get File
        run:  |
              curl https://unstable.irods.org/apt/dists/bionic/InRelease
      - name: Install iRODS Externals
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: |
              curl https://unstable.irods.org/irods-unstable-signing-key.asc | sudo apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ bionic main" | sudo tee /etc/apt/sources.list.d/renci-irods-unstable.list
              sudo apt-get update -qq
