name: build-irods-ubuntu
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:20.04','ubuntu:22.04']
    steps:
      - name: get git good
        run:  |
              apt-get update -qq
              apt-get install -qq git
              git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Prerequisites
        run:  |
              apt-get update -qq
              DEBIAN_FRONTEND=noninteractive apt-get install -qq dnsutils apt-transport-https ca-certificates
              apt-get install -qq wget curl g++ make python3-dev unixodbc libcurl4-gnutls-dev libbz2-dev zlib1g-dev libpam0g-dev libssl-dev libxml2-dev unixodbc-dev python3-psutil super odbc-postgresql libkrb5-dev python3-distro
      - name: Install libstdc++6
        run:  |
              apt-get install -qq software-properties-common
              add-apt-repository -y ppa:ubuntu-toolchain-r/test
              apt-get update -qq
              apt-get install -qq libstdc++6
      - name: Install iRODS Externals
        run:  |
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods-unstable.list
              apt-get update -qq
              apt-get install -qq \
                irods-externals-avro1.11.0-2 \
                irods-externals-boost1.81.0-0 \
                irods-externals-catch22.13.8-0 \
                irods-externals-clang-runtime13.0.0-0 \
                irods-externals-clang13.0.0-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-cppzmq4.8.1-1 \
                irods-externals-fmt8.1.1-0 \
                irods-externals-json3.10.4-0 \
                irods-externals-libarchive3.5.2-0 \
                irods-externals-nanodbc2.13.0-1 \
                irods-externals-spdlog1.9.2-1 \
                irods-externals-zeromq4-14.1.8-0
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
      - name: Build and Package
        run:  |
              cd build
              make package  # without -j to avoid GitHub Action OOM Killer (error 137)
      - name: Copy built packages
        run:  |
              mkdir ${{ matrix.container }}
              cp build/*.deb ${{ matrix.container }}
      - name: Shorten the SHA
        run:  echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: SCP built packages
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "${{ matrix.container }}/*.deb"
          target: /projects/irods/github-build-artifacts/${{ env.SHORT_SHA }}
