name: build-irods-centos
on: [push]
jobs:
  build:
    name: build-irods-on-${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7','centos:8']
    steps:
      - name: Get Public IP
        run:  |
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Install iRODS Externals
        run:  |
              sudo rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | sudo tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              sudo yum -y update
