name: build-irods-centos
on: [push, pull_request]
jobs:
  build:
    name: build-irods-on-${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7','centos:8']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get Public IP
        run:  |
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Install Dependencies
        run:  |
              sudo yum -y update
#              sudo yum -y install gcc g++ make bzip2-devel curl-devel fakeroot help2man openssl-devel pam-devel python-devel unixODBC unixODBC-devel zlib-devel
      - name: Install iRODS Externals
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 10
          command: |
              sudo rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | sudo tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              sudo yum -y update
#              sudo yum -y install irods-externals-*
#      - name: Configure CMake
#        run:  |
#              export PATH=/opt/irods-externals/cmake3.11.4-0/bin:$PATH
#              mkdir build
#              cd build
#              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
#      - name: Build and Package
#        run:  |
#              cd build
#              make package
