name: build-irods-centos
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7']
    steps:
      - name: Get git
        run:  |
              yum -y update ca-certificates
              yum -y install git
              git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v2 # cannot use newer checkout b/c node linking wrong libc https://github.com/actions/setup-node/issues/922
      - name: Shorten the SHA
        run:  echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Install Prerequisites
        run:  |
              yum -y install bind-utils wget epel-release
              yum -y install gcc g++ libstdc++-static make rpm-build bzip2-devel curl-devel fakeroot openssl-devel pam-devel python-devel unixODBC unixODBC-devel zlib-devel python36-distro
      - name: Install iRODS Externals
        run:  |
              rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              yum -y update
              yum -y install \
                irods-externals-avro1.11.0-2 \
                irods-externals-boost1.81.0-0 \
                irods-externals-catch22.13.8-0 \
                irods-externals-clang-runtime13.0.0-0 \
                irods-externals-clang13.0.0-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-cppzmq4.8.1-1 \
                irods-externals-fmt8.1.1-0 \
                irods-externals-json3.10.4-0 \
                irods-externals-libarchive3.5.2-0 \
                irods-externals-nanodbc2.13.0-1 \
                irods-externals-spdlog1.9.2-1 \
                irods-externals-zeromq4-14.1.8-0
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
              cat version.json.dist
      - name: Build and Package
        run:  |
              cd build
              make package  # without -j to avoid GitHub Action OOM Killer (error 137)
      - name: Copy built packages
        run:  |
              mkdir ${{ matrix.container }}
              cp build/*.rpm ${{ matrix.container }}
      - name: SCP built packages
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "${{ matrix.container }}/*.rpm"
          target: /projects/irods/k8s-testing/github-build-artifacts/${{ env.SHORT_SHA }}
