name: build-irods-centos
on: [push]
jobs:
  build:
    name: build-irods-on-${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7']
    steps:
      - name: Install git > v2.18 for Checkout
        run:  |
              yum install -y git
              yum install -y \
                https://repo.ius.io/ius-release-el7.rpm \
                https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
              yum swap -y git git224-core
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Prerequisites
        run:  |
              yum install -y sudo bind-utils wget
#              yum -y install gcc g++ make bzip2-devel curl-devel fakeroot help2man openssl-devel pam-devel python-devel unixODBC unixODBC-devel zlib-devel
      - name: Get Public IP
        run:  |
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Install iRODS Externals
        run:  |
              sudo rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | sudo tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              sudo yum -y update
