name: clang-format

on: [push]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run clang-format
      uses: HorstBaerbel/action-clang-format@1.4
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        excludedirs: 'build'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        style: 'file'
