name: generate-coverage
on:
#  push:
#  pull_request:
  workflow_dispatch:
#  schedule:
jobs:
  build_and_upload_packages:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:24.04']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Prerequisites
        run:  |
              apt-get update -qq
              apt-get install -qq \
                dnsutils \
                apt-transport-https \
                ca-certificates
              apt-get install -qq \
                build-essential \
                wget \
                curl \
                g++ \
                make \
                cmake \
                python3-dev \
                unixodbc \
                catch2 \
                libcurl4-gnutls-dev \
                libbz2-dev \
                libfmt-dev \
                zlib1g-dev \
                libpam0g-dev \
                libspdlog-dev \
                libssl-dev \
                libxml2-dev \
                nlohmann-json3-dev \
                unixodbc-dev \
                python3-psutil \
                odbc-postgresql \
                python3-distro \
                flex \
                bison \
                libsystemd-dev \
                libarchive-dev
      - name: Install iRODS Externals
        run:  |
              mkdir -p /etc/apt/keyrings
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | \
                gpg \
                  --no-options \
                  --no-default-keyring \
                  --no-auto-check-trustdb \
                  --homedir /dev/null \
                  --no-keyring \
                  --import-options import-export \
                  --output /etc/apt/keyrings/renci-irods-unstable-archive-keyring.pgp \
                  --import
              echo "deb [signed-by=/etc/apt/keyrings/renci-irods-unstable-archive-keyring.pgp arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | \
                tee /etc/apt/sources.list.d/renci-irods-unstable.list
              apt-get update -qq
              apt-get install -qq \
                irods-externals-boost1.81.0-2 \
                irods-externals-clang16.0.6-0 \
                irods-externals-jsoncons0.178.0-0 \
                irods-externals-nanodbc2.13.0-3
      - name: Configure CMake
        run:  |
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON -DIRODS_ENABLE_ALL_TESTS=YES -DIRODS_ENABLE_COVERAGE=ON ../
      - name: Build and Package
        run:  |
              cd build
              make package
              cd ..
              mkdir debs
              cp build/*.deb debs/
      - name: Install Dev Package
        run:  |
              cd build
              apt install -y -qq ./irods-dev* ./irods-runtime*
      - name: Build iCommands
        run:  |
              apt install -y -qq git
              git clone https://github.com/irods/irods_client_icommands
              cd irods_client_icommands
              mkdir build
              cd build
              cmake -DIRODS_ENABLE_COVERAGE=ON ../
              make package
              cd ..
              cp build/*.deb ../debs/
      - name: Upload Built iRODS Packages
        uses: actions/upload-artifact@v4
        with:
          name: thepackages
          path: debs

  test_with_coverage:
    needs: build_and_upload_packages
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:24.04']
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Download DEBs
        uses: actions/download-artifact@v5
        with:
          name: thepackages
          path: debs

      - name: Install Dependencies
        run:  |
              apt update
              apt install -y -qq git python3 python3-venv
              # get compose as python module
              git clone https://github.com/docker/compose
              cd compose
              git checkout 1.29.2
              sed -i 's/, < 6/, < 7/g' setup.py
              sed -i 's/kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)/kwargs = kwargs_from_env(environment=environment)/g' compose/cli/docker_client.py
              cd ..
              python3 -mvenv venv
              . venv/bin/activate
              pip install ./compose

      - name: Launch iRODS server via testing environment
        run:  |
              mkdir -p theoutput/core_tests
              mkdir -p theoutput/unit_tests
              . venv/bin/activate
              git clone https://github.com/irods/irods_testing_environment
              cd irods_testing_environment
              python3 run_core_tests.py \
                --verbose \
                --project-directory ./projects/ubuntu-24.04/ubuntu-24.04-postgres-17 \
                --irods-package-directory ../debs \
                --output-directory $(pwd)/../theoutput/core_tests \
                --tests test_imkdir
              python3 run_unit_tests.py \
                --verbose \
                --project-directory ./projects/ubuntu-24.04/ubuntu-24.04-postgres-17 \
                --irods-package-directory ../debs \
                --output-directory $(pwd)/../theoutput/unit_tests

      - name: Upload Output Directory
        uses: actions/upload-artifact@v4
        with:
          name: theoutput
          path: theoutput
